### ISSUE TITLE
eZpublish / .tpl files syntax match

### ISSUE THREAD

**Issue by rudzboy** [sirreal/eZ-Publish-Syntax#4]
Maybe it happened to others but I had to do an extra operation in ST2 to make this work.

After installing plugin using Package Control,
ST2 still opens my .tpl files with the HTML syntax.

What to do ->

1) Open a .tpl file in editor
2) Go to Menu -> View -> Syntax -> Open all with current extension as....
3 ) Select eZPublish -> TPL Files

So far, your syntax highlighting is great. Thank you for this !

**Comment by sirreal** [comment]
As far as I know this is normal behavior.

If you think it would be helpful to include in the documentation or installation instructions, please open a new pull request with the improvements.

Thanks!

**Comment by rudzboy** [comment]
I'm new to Sublime Text, but I had other syntax highlighting packages installed and I had no need to do this operation.

**Comment by sirreal** [comment]
In theory, [these lines](https://github.com/sirreal/eZ-Publish-Syntax/blob/dca21e3d2eef0f9510998f58512d73e552e4c196/eZ_tpl.tmLanguage#L5-L9) should assosciate `.tpl` with the syntax provided by this pluign. It may be that `.tpl` is common enough to be previously associated with another syntax, which needs to be overridden by the user.

I'm speculating, but I do believe the plugin `fileTypes` associations are correctly implemented. However, I'd be happy to accept any improvements to this plugin.

**Comment by rudzboy** [comment]
As I said I'm new to ST but I agree that it looks correct.
I'll try to save some time to check whether something else is needed.

Thx
